<a href="https://colab.research.google.com/github/lishikajain2006-lgtm/SYNTECX-HUB/blob/main/Numpy_Data_Explorer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1D Array
arr1 = np.array([1, 2, 3, 4])

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Special arrays
zeros = np.zeros((2, 3))
ones = np.ones((2, 2))
range_arr = np.arange(0, 10, 2)

print(arr1)
print(arr2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr1[0])        # First element
print(arr2[1, 2])    # Row 1, Col 2

# Slicing
print(arr1[1:3])
print(arr2[:, 1])    # All rows, 2nd column

1
6
[2 3]
[2 5]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(a ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


In [ ]:
#Step 6: Axis-wise Operations
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(np.sum(arr))         # Total sum
print(np.sum(arr, axis=0)) # Column-wise
print(np.sum(arr, axis=1)) # Row-wise

21
[5 7 9]
[ 6 15]


In [ ]:
#Step 7: Statistical Operations
data = np.array([10, 20, 30, 40, 50])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.max(data))
print(np.min(data))

30.0
30.0
14.142135623730951
50
10


In [ ]:
#Step 8: Reshaping & Broadcasting
arr = np.arange(6)

reshaped = arr.reshape(2, 3)
print(reshaped)

# Broadcasting
a = np.array([1, 2, 3])
b = 2
print(a + b)

[[0 1 2]
 [3 4 5]]
[3 4 5]


In [ ]:
#Step 9: Save & Load Arrays
# Save
np.save('my_array.npy', arr1)

# Load
loaded = np.load('my_array.npy')
print(loaded)

[1 2 3 4]


In [ ]:
#Step 10: Performance Comparison
import time

# Python list
list1 = list(range(1000000))
start = time.time()
list2 = [i*2 for i in list1]
print("List time:", time.time() - start)

# NumPy array
arr = np.arange(1000000)
start = time.time()
arr2 = arr * 2
print("NumPy time:", time.time() - start)

List time: 0.06666374206542969
NumPy time: 0.005601167678833008
